# Generated by Django 3.2.15 on 2023-07-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='owner',
        ),
    ]
