# Generated by Django 3.2.15 on 2023-08-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userr',
            old_name='username',
            new_name='uname',
        ),
    ]
