# Generated by Django 3.2.15 on 2023-08-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230811_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
