# Generated by Django 3.2.15 on 2023-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
            preserve_default=False,
        ),
    ]
